### ISSUE TITLE
disable-line works for rules, but not syntax errors.

### ISSUE THREAD

**Issue by wpdrush21** [adrienverge/yamllint#69] opened 2017-09-08 18:24 UTC
We are using yamllint on files that will be used as helm charts, where syntax such as

`value: {{ .Values.service.name }}{{ if eq .Values.environment "staging" }} (staging){{ end }}`

is completely valid. Ideally we would be able to skip this line from running yamllint, but since it is a syntax-error, and not an issue with a given rule, the disable-line functionality `# yamllint disable-line` doesn't work.

Ideally disable-line would either skip syntax-errors as well as rules, or there could be a separate rule `ignore-line` for this case.

**Comment by adrienverge** [comment] 2017-09-11 08:20
Closing as duplicate of #61 and #65.

Sorry but we currently do not have a way to disable lines from the syntax error check, as parsing the whole file relies on a YAML parser. Any input to go beyond that is welcome!

By the way the snippet you wrote is not *completely valid* YAML, it needs to be pre-processed to be understood by any YAML parser.

**Closed by adrienverge** 2017-09-11 08:20 UTC
