### ISSUE TITLE
Add support for custom file extensions

### ISSUE THREAD

**Issue by grzesuav** [adrienverge/yamllint#192] opened 2019-07-15 07:39 UTC
Currently when running with `.` (current directory) only `.yml` and `.yaml` files are checked. Would like to have an option to configure file extensions.

**Comment by adrienverge** [comment] 2019-07-15 08:33
Isn'it a duplicate of https://github.com/adrienverge/yamllint/issues/85?

**Closed by adrienverge** 2019-07-15 08:33 UTC
