### ISSUE TITLE
Ignoring certain tags?

### ISSUE THREAD

**Issue by soostdijck** [adrienverge/yamllint#87] opened 2017-11-16 09:24 UTC
Hi,

I'd like to use yamllint to check my saltstack state files. However these can also contain jinja2 templating language that I want to be ignored by yamllint. Is there any way to configure certain tags to be ignored? For example anything encased in curly brackets { ... }

p.s this would be similarly useful for ansible, puppet and probably many more configs.

Thanks,
Sjoerd.

**Comment by adrienverge** [comment] 2017-11-16 11:12
Hi,

This is a duplicate of #61 (and others).

Sorry, the files you mention need to be preprocessed to become valid YAML, and yamllint can only parse real YAML.

As of today I do not know any workaround.

**Closed by adrienverge** 2017-11-16 11:12 UTC
