### ISSUE TITLE
indentation.spaces ignored, when using tag and anchor

### ISSUE THREAD

**Issue by bartsch** [adrienverge/yamllint#435] opened 2022-01-05 13:40 UTC
(yamllint 1.26.3)

Having a tag and an anchor in an example.yaml like this:
```yaml
---
pretty: !useless &example
    purpose: trigger indentation error
```
and running yamllint:
`yamllint --config-data "{extends: default, rules: {indentation: {spaces: 4}}}" example.yaml`
raises the error:
```
example.yaml
  3:5       error    wrong indentation: expected 8 but found 4  (indentation)
```

So, it ignores `spaces: 4` and wants _purpose_ to be aligned with the tag at column 8.
- Swapping the tag and anchor doesn't change the result - the error remains the same.
- Removing either tag or anchor works.

**Comment by adrienverge** [comment] 2022-01-05 16:05
Interesting!

I guess there's something to fix around
https://github.com/adrienverge/yamllint/blob/4f1bbc3/yamllint/rules/indentation.py#L452-L461

Contributions are welcome.

**Comment by adrienverge** [comment] 2023-01-10 17:42
Closing as a duplicate of https://github.com/adrienverge/yamllint/issues/78.

**Closed by adrienverge** 2023-01-10 17:42 UTC
