### ISSUE TITLE
Enhancement: Option to apply style

### ISSUE THREAD

**Issue by mcandre** [adrienverge/yamllint#269] opened 2020-05-15 21:09 UTC
For large collections of YAML files, it would be helpful to offer an automated CLI flag to go ahead and format the files per yamllint configuration. Maybe a `--apply` option?

**Comment by adrienverge** [comment] 2020-05-16 04:18
Isn't it a duplicate of #209, #62, #230 and #231?

**Closed** 2023-02-02 08:13 UTC
