### ISSUE TITLE
Read list of rules directly from disk

### ISSUE THREAD

**Issue by ChristianWeissCG** [adrienverge/yamllint#168] opened 2019-03-24 18:25 UTC
I am writing new rules for yamllint at the moment.
Instead of a static definition in rules/__init_.py it would be cool if you can import dynamically from disk, and also read rule ID from rule file dynamically.

A command line option to point yamllint to custom rule dir to import additional rules and rulesets (e.g. similar to 'relaxed') would make it easyer to have different rulesets for different projects (e.g im my CI/CD server).

**Comment by adrienverge** [comment] 2019-03-24 23:46
Hi, it looks like a duplicate of https://github.com/adrienverge/yamllint/issues/123. Please reopen if it's not.

**Closed by adrienverge** 2019-03-24 23:46 UTC

**Comment by ChristianWeissCG** [comment] 2019-03-25 11:18
No now see that there is a `-c` option to select a custom ruleset. The custom rules can be imported using `--extra-rules` (when #123 is implemented). So, my ticket is a dublicate.
