### ISSUE TITLE
Autofix support

### ISSUE THREAD

**Issue by mwgamble** [adrienverge/yamllint#535] opened 2023-02-01 21:56 UTC
There's a fair few issues that yamllint reports on that can be trivially autofixed. Examples include missing the document start indicator, and quoting strings. It would be great if yamllint had this functionality, as it would greatly speed up the adoption time for older codebases.

**Comment by andrewimeson** [comment] 2023-02-01 22:21
Unlikely to be added, but check out (yamlfix)[https://github.com/lyz-code/yamlfix] which produces yamllint-compliant auto-formatted YAML. It also does nice things like remove superfluous quoting. I use it 10s of times per day, but in my editor (vim + ALE), as well as a pre-commit hook.

**Comment by adrienverge** [comment] 2023-02-02 08:13
Hello, +1 with @andrewimeson.

Closing this as a duplicate of #62, #209, #230, #231 and #269.

**Closed by adrienverge** 2023-02-02 08:13 UTC
